title: test
description: test serverless
template:
  repo: test-template
  name: test
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: intro to test
    description: learn how to create your first test
    event: content_reference
    link: '{{ repoUrl }}'
    actions: []
  - title: part 2 - test invocations
    actions: []
    link: '{{ repoUrl }}'
    description: learn how to create your first test
  - title: 'step 3 '
    actions: []
    description: '- Connecting test application to a web front end '
    link: '{{ repoUrl }}'
  - title: New step
    actions: []
